# ecoding:utf-8
import sys

reload(sys)
sys.setdefaultencoding('utf-8')
domain_classtype = {
    "4shared.com": "在线存储分享",
    "brothersoft.com": "软件",
    "wikipedia.org": "字典和百科全书",
    "nifty.com": "ISPs",
    "360.cn": "安全软件",
    "tripadvisor.com": "医院",
    "hi5.com": "社交网络",
    "1stwebgame.com": "网页游戏",
    "yandex.ru": "搜索引擎",
    "liveperson.net": "Apparel",
    "amazon.de": "在线书店",
    "globo.com": "新闻",
    "xunlei.com": "视频下载",
    "baidu.com": "搜索引擎",
    "paipai.com": "购物网站",
    "netlog.com": "社交网络",
    "addthis.com": "Java",
    "netflix.com": "电影租赁",
    "craigslist.org": "分类信息",
    "expedia.com": "旅行预订",
    "4399.com": "在线游戏",
    "com.com": "科技新闻",
    "126.com": "项目",
    "naver.com": "搜索引擎",
    "about.com": "问答服务",
    "reference.com": "字典和百科全书",
    "cnn.com": "新闻",
    "walmart.com": "在线购物",
    "blogspot.com": "博客服务",
    "depositfiles.com": "在线存储分享",
    "getpersonas.com": "互联网软件/浏览器",
    "geocities.jp": "虚拟主机",
    "optmd.com": "个人网站",
    "nytimes.com": "报纸",
    "flickr.com": "视频网站",
    "photobucket.com": "视频网站",
    "ku6.com": "多媒体",
    "chinamobile.com": "在线服务",
    "skype.com": "网络电话",
    "microsoft.com": "软件",
    "ask.com": "搜索引擎",
    "hatena.ne.jp": "博客服务",
    "odnoklassniki.ru": "个人网站",
    "megavideo.com": "视频网站",
    "reuters.com": "新闻",
    "target.com": "Mass Merchants & Department Stores",
    "renren.com": "社交网络",
    "tudou.com": "视频网站",
    "tagged.com": "社交网络",
    "filestube.com": "在线存储分享",
    "tianya.cn": "在线社区",
    "gougou.com": "在线服务",
    "rambler.ru": "门户网站",
    "alipay.com": "在线支付",
    "xici.net": "在线社区",
    "2345.com": "医院",
    "daum.net": "在线社区",
    "joy.cn": "电影",
    "163.com": "门户网站",
    "dailymotion.com": "视频网站",
    "dell.com": "Forum & Chat Providers",
    "overture.com": "搜索引擎",
    "pconline.com.cn": "Mobile Phones",
    "orkut.com": "社交网络",
    "hao123.com": "网址导航",
    "taringa.net": "在线娱乐",
    "hexun.com": "投资理财",
    "vkontakte.ru": "社交网络",
    "seesaa.net": "搜索引擎",
    "taobao.com": "网络购物",
    "softonic.com": "电脑主机",
    "mozilla.org": "互联网软件/浏览器",
    "weather.com.cn": "天气",
    "xinhuanet.com": "新闻",
    "amazon.com": "网络购物",
    "conduit.com": "网络广告",
    "kaixin001.com": "在线服务",
    "yahoo.com": "门户网站",
    "commentcamarche.net": "电脑主机",
    "tripod.com": "虚拟主机",
    "bbc.co.uk": "新闻",
    "cnet.com": "科技新闻",
    "miniclip.com": "在线游戏",
    "2ch.net": "在线沟通服务",
    "adobe.com": "项目",
    "hp.com": "教育资源",
    "biglobe.ne.jp": "门户网站",
    "livedoor.com": "门户网站",
    "zedo.com": "电子商务",
    "goo.ne.jp": "在线服务",
    "soso.com": "在线娱乐",
    "mywebsearch.com": "社交网络",
    "zing.vn": "ERP",
    "msn.com": "门户网站",
    "sina.com.cn": "门户网站",
    "ameblo.jp": "博客服务",
    "exblog.jp": "博客服务",
    "ebay.com": "购物网站",
    "live.com": "搜索引擎",
    "people.com.cn": "在线娱乐",
    "kakaku.com": "网络购物 Portals & 搜索引擎",
    "imageshack.us": "在线存储分享",
    "bankofamerica.com": "在线支付",
    "mediafire.com": "在线存储分享",
    "weather.com": "天气",
    "youku.com": "视频网站",
    "mail.ru": "在线沟通服务",
    "cocolog-nifty.com": "在线服务",
    "amazon.co.uk": "在线书店",
    "java.com": "Java",
    "douban.com": "社交网络",
    "alexa.com": "Search Engine Optimization & Marketing",
    "mozilla.com": "互联网软件/浏览器",
    "fbcdn.net": "语言学习",
    "zynga.com": "在线游戏",
    "chinanews.com.cn": "新闻",
    "twitter.com": "在线沟通服务",
    "rapidshare.com": "在线存储分享",
    "windows.com": "操作系统",
    "xtendmedia.com": "Web Design & Development",
    "answers.com": "字典和百科全书",
    "ocn.ne.jp": "ISPs",
    "allabout.co.jp": "在线服务",
    "blogger.com": "博客服务",
    "unionsky.cn": "Online Goodies",
    "livedoor.jp": "博客服务",
    "hotmail.com": "在线沟通服务",
    "yahoo.co.jp": "门户网站",
    "ameba.jp": "博客服务",
    "114la.com": "网址导航",
    "terra.com.br": "Lyrics & Tabs",
    "atpanel.com": "网络购物",
    "sourceforge.net": "Open Source",
    "iefxz.com": " ",
    "att.com": "在线服务",
    "mixi.jp": "社交网络",
    "chase.com": "在线支付",
    "apple.com": "操作系统",
    "56.com": "多媒体",
    "tom.com": "门户网站",
    "wordpress.com": "博客服务",
    "alibaba.com": "电子商务",
    "tinypic.com": "视频网站",
    "youdao.com": "搜索引擎",
    "mapquest.com": "Maps & Geography",
    "aol.com": "门户网站",
    "narod.ru": "博客服务",
    "qq.com": "在线沟通服务",
    "paypal.com": "在线支付",
    "so-net.ne.jp": "ISPs",
    "eastmoney.com": "投资理财",
    "nate.com": "门户网站",
    "zol.com.cn": "硬件",
    "vk.com": "搜索引擎",
    "tinyurl.com": "在线服务",
    "partypoker.com": "赌博网站s",
    "avg.com": "Antivirus & Malware",
    "megaupload.com": "在线存储分享",
    "sohu.com": "门户网站",
    "ifeng.com": "新闻",
    "rakuten.co.jp": "网络购物 Portals & 搜索引擎",
    "myspace.com": "社交网络",
    "metacafe.com": "视频网站",
    "sakura.ne.jp": "虚拟主机",
    "nih.gov": "Medical Literature & Resources",
    "linkedin.com": "社交网络",
    "thepiratebay.org": "在线存储分享",
    "bing.com": "搜索引擎",
    "ebay.co.uk": "购物网站",
    "cyworld.com": "门户网站",
    "bit.ly": "在线存储分享",
    "39.net": "健康",
    "scribd.com": "E-Books",
    "facebook.com": "社交网络",
    "badoo.com": "社交网络",
    "58.com": "分类信息",
    "ehow.com": "问答服务",
    "livejournal.com": "博客服务",
    "uol.com.br": "门户网站",
    "game2.com.cn": "游戏网站",
    "ning.com": "社交网络",
    "pps.tv": "视频网站",
    "free.fr": "ISPs",
    "go.com": "门户网站",
    "thefreedictionary.com": "字典和百科全书",
    "7k7k.com": "在线游戏",
    "cctv.com": "TV",
    "ebay.de": "购物网站",
    "fc2.com": "博客服务",
    "imdb.com": "电影",
    "amazon.co.jp": "网络购物 Portals & 搜索引擎",
    "mop.com": "Roleplaying Games",
    "wikimedia.org": "字典和百科全书",
    "browserchoice.eu": "互联网软件/浏览器",
    "soufun.com": "房产资讯",
    "infoseek.co.jp": "门户网站",
    "kugou.com": "电影",
    "sogou.com": "门户网站",
    "mcafee.com": "安全软件",
    "hotfile.com": "在线存储分享"
}
